"use client";
import { useEffect, useMemo, useState, useRef } from "react";
import { Plane, LayoutDashboard, Tickets, ChartNoAxesCombined, SlidersHorizontal, Database, BookOpen, Download, ArrowUpRight, CalendarDays, TriangleAlert, ChevronRight, Search, ArrowDownUp, Check, CircleCheck, Clock3, TrendingUp, ShieldCheck, Info, RotateCcw, ExternalLink } from "lucide-react";
import { SidebarProvider, Sidebar, SidebarHeader, SidebarContent, SidebarMenu, SidebarMenuItem, SidebarMenuButton, SidebarFooter, SidebarTrigger, useSidebar } from "@/components/ui/sidebar";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select";
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from "@/components/ui/sheet";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Slider } from "@/components/ui/slider";
import { Toaster } from "@/components/ui/sonner";
import { toast } from "sonner";
import { ResponsiveContainer, ComposedChart, BarChart, Bar, Line, Area, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ReferenceLine } from "recharts";
import rawPortfolio from "@/public/data/portfolio.json";
import { type Contract, type Portfolio, sum, daysUntil, money, number, shortDate, monthLabel, recommend, summarize, exportCsv } from "@/lib/analytics";
const data=rawPortfolio as unknown as Portfolio;
const nav=[{name:"Overview",icon:LayoutDashboard},{name:"Flight inventory",icon:Tickets},{name:"Demand forecast",icon:ChartNoAxesCombined},{name:"Scenario planner",icon:SlidersHorizontal},{name:"Data quality",icon:Database},{name:"Project & methodology",icon:BookOpen}];
function Picker({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:{value:string;label:string}[];label:string}){
 return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="filter-select"><SelectValue/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>;
}
function NavigationMenu({view,navigate}:{view:string;navigate:(name:string)=>void}){const {setOpenMobile}=useSidebar();return <SidebarMenu>{nav.map(n=><SidebarMenuItem key={n.name}><SidebarMenuButton isActive={view===n.name} onClick={()=>{navigate(n.name);setOpenMobile(false)}}><n.icon/><span>{n.name}</span>{n.name==="Flight inventory"&&<span className="nav-count">{data.contracts.length}</span>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu>;}
function Badge({status}:{status:string}){return <span className={"status "+(status==="Deadline passed"?"danger":status==="Review release"?"warning":status==="Strong demand"||status==="On track"?"success":"neutral")}>{status}</span>}
function Metric({label,value,note,icon:Icon,tone=""}:{label:string;value:string;note:string;icon:typeof Plane;tone?:string}){return <div className={"metric "+tone}><div className="metric-top">{label}<Icon size={17}/></div><strong>{value}</strong><small>{note}</small></div>}
function download(content:string,name:string,type="text/csv;charset=utf-8"){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const chartTooltip={contentStyle:{borderRadius:8,border:"1px solid #dfe7ef",fontSize:12,boxShadow:"0 5px 20px #19364a10"},labelStyle:{fontWeight:600,color:"#19364a"}};

export default function Dashboard(){
 const [view,setView]=useState("Overview"),[region,setRegion]=useState("all"),[origin,setOrigin]=useState("all"),[horizon,setHorizon]=useState("all");
 const [search,setSearch]=useState(""),[risk,setRisk]=useState("all"),[sortAsc,setSortAsc]=useState(true),[page,setPage]=useState(1);
 const [selected,setSelected]=useState<Contract|null>(null),[reviewed,setReviewed]=useState<string[]>([]),[loaded,setLoaded]=useState(false);
 const [forecastRoute,setForecastRoute]=useState("all"),[uplift,setUplift]=useState(0),[buffer,setBuffer]=useState(2),[strategy,setStrategy]=useState("release");
 useEffect(()=>{try{const ids=JSON.parse(localStorage.getItem("touring-reviewed-v1")||"[]");if(Array.isArray(ids))setReviewed(ids.filter(x=>typeof x==="string"));}catch{}setLoaded(true)},[]);
 useEffect(()=>{if(loaded)localStorage.setItem("touring-reviewed-v1",JSON.stringify(reviewed))},[reviewed,loaded]);
 const rows=useMemo(()=>data.contracts.filter(c=>(region==="all"||c.region===region)&&(origin==="all"||c.origin===origin)&&(horizon==="all"||daysUntil(c.departure,data.asOf)<=Number(horizon))),[region,origin,horizon]);
 const totals=summarize(rows,data.asOf);
 const currentState=useRef({region,origin,horizon,rows,totals});currentState.current={region,origin,horizon,rows,totals};
 const routeIds=[...new Set(rows.map(c=>c.route))];
 useEffect(()=>{setPage(1)},[region,origin,horizon,search,risk]);
 useEffect(()=>{if(forecastRoute!=="all"&&!routeIds.includes(forecastRoute))setForecastRoute("all")},[region,origin,horizon,forecastRoute,routeIds.join(",")]);
 const navigate=(name:string)=>{setView(name);window.scrollTo({top:0,behavior:"smooth"})};
 const attention=rows.filter(c=>{const r=recommend(c,data.asOf);return r.days<0||(r.days<=14&&r.release>0)}).sort((a,b)=>recommend(a,data.asOf).days-recommend(b,data.asOf).days);
 const monthData=[...new Set(rows.map(c=>c.departure.slice(0,7)))].sort().map(m=>{const cs=rows.filter(c=>c.departure.startsWith(m));return {month:monthLabel(m),Booked:sum(cs,c=>c.booked),Forecast:sum(cs,c=>c.forecastPax),Committed:sum(cs,c=>c.seats),Budget:sum(cs,c=>c.budgetPax),Revenue:sum(cs,c=>c.forecastPax*c.sellPrice),BudgetRevenue:sum(cs,c=>c.budgetPax*c.sellPrice)}});
 const filtered=rows.filter(c=>(c.id+" "+c.tour+" "+c.route+" "+c.airline).toLowerCase().includes(search.toLowerCase())).filter(c=>{const r=recommend(c,data.asOf);return risk==="all"||risk==="due"&&r.days>=0&&r.days<=14||risk==="overdue"&&r.days<0||risk==="release"&&r.release>0||risk==="reviewed"&&reviewed.includes(c.id)}).sort((a,b)=>sortAsc? a.releaseDate.localeCompare(b.releaseDate):b.releaseDate.localeCompare(a.releaseDate));
 const bestAction=rows.filter(c=>recommend(c,data.asOf).release>0).sort((a,b)=>recommend(b,data.asOf).benefit-recommend(a,data.asOf).benefit)[0];
 const ly=sum(data.priorYear.filter(p=>rows.some(c=>c.id===p.contractId)),p=>p.bookedAtComparableLeadTime);
 const yoy=ly?(totals.booked/ly-1)*100:0;
 const activeMarketRoutes=forecastRoute==="all"?routeIds:[forecastRoute];
 const holdout=data.backtests.filter(b=>b.split==="holdout"&&activeMarketRoutes.includes(b.route));
 const wape=holdout.length?sum(holdout,b=>b.absoluteError)/sum(holdout,b=>b.actual)*100:0;
 const chartMonths=[...new Set([...data.market.filter(m=>m.month>="2025-01").map(m=>m.month),...data.predictions.map(m=>m.month)])].sort();
 const marketChart=chartMonths.map(m=>{const actual=data.market.filter(x=>x.month===m&&activeMarketRoutes.includes(x.route));const predicted=data.predictions.filter(x=>x.month===m&&activeMarketRoutes.includes(x.route));return {key:m,month:monthLabel(m),Actual:actual.length?sum(actual,x=>x.outbound):null,Forecast:predicted.length?sum(predicted,x=>x.forecast):m===data.marketThrough?sum(actual,x=>x.outbound):null,band:predicted.length?[sum(predicted,x=>x.lower),sum(predicted,x=>x.upper)]:undefined}});
 const scenario=rows.map(c=>({c,...recommend(c,data.asOf,uplift,buffer,strategy==="release")}));
 const baselineMargin=sum(scenario,r=>r.baselineMargin),scenarioMargin=sum(scenario,r=>r.margin);
 const releases=sum(scenario,r=>r.release),benefit=scenarioMargin-baselineMargin;
 const markReviewed=(id:string)=>{setReviewed(ids=>ids.includes(id)?ids.filter(x=>x!==id):[...ids,id]);toast.success(reviewed.includes(id)?"Review reopened":"Marked reviewed on this device");};
 const exportReport=()=>{download(exportCsv(rows,data.asOf),"touring-control-inventory-"+data.asOf+".csv");toast.success("Filtered inventory report exported");};

 useEffect(()=>{
  type Registry={registerTool:(t:object,o:{signal:AbortSignal})=>void|Promise<void>};
  const context=(document as unknown as {modelContext?:Registry}).modelContext;if(!context?.registerTool)return;
  const lifecycle=new AbortController();
  const valid=(input:unknown)=>{if(!input||typeof input!=="object")throw new Error("Expected an object");return input as Record<string,unknown>};
  const register=(tool:object)=>{try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}};
  register({name:"read_inventory_summary",title:"Read inventory summary",description:"Read the current filtered simulated inventory metrics and snapshot date.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({asOf:data.asOf,provenance:"Simulated commercial inventory",...currentState.current.totals})});
  register({name:"configure_inventory_filters",title:"Configure inventory filters",description:"Change region, origin and departure horizon using the dashboard's visible controls.",inputSchema:{type:"object",properties:{region:{type:"string",enum:["all","Asia","Oceania"]},origin:{type:"string",enum:["all","Brisbane","Sydney","Melbourne"]},horizon:{type:"string",enum:["all","60","120"]}},additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{const x=valid(input);if(Object.keys(x).some(k=>!["region","origin","horizon"].includes(k)))throw new Error("Unexpected field");const r=x.region??currentState.current.region,o=x.origin??currentState.current.origin,h=x.horizon??currentState.current.horizon;if(!["all","Asia","Oceania"].includes(String(r))||!["all","Brisbane","Sydney","Melbourne"].includes(String(o))||!["all","60","120"].includes(String(h)))throw new Error("Invalid filter");setRegion(String(r));setOrigin(String(o));setHorizon(String(h));return new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve({region:r,origin:o,horizon:h}))))}});
  register({name:"configure_release_scenario",title:"Configure release scenario",description:"Set demand change, safety seats and release strategy in the visible scenario planner. This never releases airline seats.",inputSchema:{type:"object",properties:{demandChange:{type:"integer",minimum:-35,maximum:35},buffer:{type:"integer",minimum:0,maximum:8},strategy:{type:"string",enum:["release","retain"]}},required:["demandChange","buffer","strategy"],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{const x=valid(input);if(!Number.isInteger(x.demandChange)||Number(x.demandChange)<-35||Number(x.demandChange)>35||!Number.isInteger(x.buffer)||Number(x.buffer)<0||Number(x.buffer)>8||!["release","retain"].includes(String(x.strategy)))throw new Error("Invalid scenario");setUplift(Number(x.demandChange));setBuffer(Number(x.buffer));setStrategy(String(x.strategy));setView("Scenario planner");const result=currentState.current.rows.map(c=>recommend(c,data.asOf,Number(x.demandChange),Number(x.buffer),x.strategy==="release"));return new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve({releasedSeats:sum(result,r=>r.release),contribution:sum(result,r=>r.margin),provenance:"Illustrative scenario"}))))}});
  return()=>lifecycle.abort();
 },[]);

 return <SidebarProvider style={{"--sidebar-width":"240px"} as React.CSSProperties}>
 <Toaster position="bottom-right"/>
 <Sidebar className="navigation"><SidebarHeader><div className="brand"><span className="brand-mark"><Plane size={21}/></span><div>touring<span>control</span></div></div><div className="workspace">COMMERCIAL WORKSPACE</div></SidebarHeader>
 <SidebarContent><NavigationMenu view={view} navigate={navigate}/></SidebarContent>
 <SidebarFooter><div className="sidebar-note"><span className="small-label">THE INVENTORY QUESTION</span><p>The right seats.<br/>The right time.<br/>Less exposure.</p><span className="note-line"/></div><div className="profile"><span>TS</span><div>Portfolio workspace<small>Independent case study</small></div></div></SidebarFooter></Sidebar>
 <main className="main-shell"><header className="topbar"><div className="breadcrumb"><SidebarTrigger/><span>My Touring case study</span><ChevronRight size={14}/><b>{view}</b></div><div className="snapshot"><CalendarDays size={15}/>9 October 2026<span className="demo-tag">DEMO</span></div></header>
 <div className="page-content">
 <div className="page-heading"><div><div className="eyebrow">{view==="Overview"?"PORTFOLIO INTELLIGENCE":view==="Demand forecast"?"OFFICIAL MARKET DATA":view==="Scenario planner"?"COMMERCIAL DECISION LAB":"TOURING OPERATIONS"}</div><h1>{view==="Overview"?"Every seat. A smarter decision.":view}</h1><p>{view==="Overview"?"Stay ahead of demand, release deadlines and commercial exposure.":view==="Demand forecast"?"Real route history. Transparent forecasts. Measured accuracy.":view==="Scenario planner"?"Explore the trade-off between holding seats and protecting contribution.":view==="Flight inventory"?"Review commitments, booking pace and release windows in one place.":view==="Data quality"?"Trust the numbers by tracing every record through the pipeline.":"The business problem, analytical approach and evidence behind the project."}</p></div><button className="btn primary" onClick={exportReport}><Download size={16}/>Export report</button></div>
 <div className="filterbar"><span className="filter-label"><SlidersHorizontal size={15}/>Portfolio filters</span>
 <Picker label="Region" value={region} onChange={setRegion} options={[{value:"all",label:"All regions"},{value:"Asia",label:"Asia"},{value:"Oceania",label:"Oceania"}]}/>
 <Picker label="Departure city" value={origin} onChange={setOrigin} options={[{value:"all",label:"All origins"},...["Brisbane","Sydney","Melbourne"].map(s=>({value:s,label:s}))]}/>
 <Picker label="Departure horizon" value={horizon} onChange={setHorizon} options={[{value:"all",label:"All departures"},{value:"60",label:"Next 60 days"},{value:"120",label:"Next 120 days"}]}/>
 {(region!=="all"||origin!=="all"||horizon!=="all")&&<button className="reset-btn" aria-label="Reset portfolio filters" onClick={()=>{setRegion("all");setOrigin("all");setHorizon("all")}}><RotateCcw size={14}/></button>}
 <span className="filter-source">AUD · Snapshot: 9 Oct 2026</span></div>
 {rows.length===0?<div className="empty"><Search size={30}/><h2>No departures match these filters</h2><p>Choose another origin, region or departure horizon.</p><button className="btn" onClick={()=>{setRegion("all");setOrigin("all");setHorizon("all")}}>Reset filters</button></div>:<>
 {view==="Overview"&&<>
 <div className="metrics"><Metric label="Contracted seats" value={number(totals.seats)} note={rows.length+" upcoming departures"} icon={Tickets}/><Metric label="Booked utilisation" value={totals.utilisation.toFixed(1)+"%"} note={(yoy>=0?"+":"")+yoy.toFixed(1)+"% passengers vs simulated prior year"} icon={ChartNoAxesCombined}/><Metric label="Unbooked commitment" value={money(totals.exposure,true)} note="Gross seat cost · not a realised loss" icon={Plane}/><Metric label="Upcoming release windows" value={String(totals.due)} note={"Due in 14 days · "+totals.overdue+" passed deadlines"} icon={Clock3} tone="attention-metric"/></div>
 <div className="overview-grid"><section className="panel"><div className="panel-title"><div><h2>Bookings meet commitments</h2><p>Passenger position by departure month · simulated portfolio</p></div><span className="chip">Nov 26 – Apr 27</span></div><div className="chart-container" role="img" aria-label="Booked and forecast passengers compared with contracted seats by month"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={monthData} margin={{top:8,right:8,left:-18,bottom:0}}><CartesianGrid stroke="#edf2f6" vertical={false}/><XAxis dataKey="month" tick={{fill:"#8094a5",fontSize:11}} tickLine={false} axisLine={false}/><YAxis tick={{fill:"#8094a5",fontSize:11}} axisLine={false} tickLine={false}/><Tooltip {...chartTooltip}/><Legend iconSize={8} wrapperStyle={{fontSize:11,paddingTop:10}}/><Bar dataKey="Booked" fill="#2864e9" radius={[4,4,0,0]} maxBarSize={25}/><Bar dataKey="Forecast" fill="#b8cdef" radius={[4,4,0,0]} maxBarSize={25}/><Line dataKey="Committed" stroke="#2d536e" strokeWidth={2} strokeDasharray="4 4" dot={false}/></ComposedChart></ResponsiveContainer></div><div className="chart-note"><Info size={13}/>Forecast passengers use an illustrative booking curve; market forecasts are separate.</div></section>
 <section className="panel insight-panel"><span className="eyebrow">YOUR NEXT BEST ACTION</span><h2>{bestAction?"Make room for a\nbetter outcome.":"Your portfolio is\non track."}</h2>{bestAction?<><p>Review <b>{bestAction.route}</b>, departing {shortDate(bestAction.departure)}. The base case suggests releasing <b>{recommend(bestAction,data.asOf).release} seats</b> while keeping a two-seat demand buffer.</p><div className="insight-value">{money(recommend(bestAction,data.asOf).benefit)}<span>illustrative contribution improvement</span></div><button className="btn" onClick={()=>setSelected(bestAction)}>Review recommendation <ChevronRight size={16}/></button></>:<p>No release opportunities under the current assumptions.</p>}<div className="insight-foot"><ShieldCheck size={17}/><span>Contract limits and deadlines applied. Product Manager review required before execution.</span></div></section></div>
 <div className="lower-grid"><section className="panel"><div className="panel-title"><div><h2>Attention before the deadline</h2><p>{attention.length} commitments need a closer look</p></div><button className="text-btn" onClick={()=>{setRisk("all");navigate("Flight inventory")}}>View inventory<ChevronRight size={14}/></button></div>
 {attention.slice(0,3).map(c=>{const r=recommend(c,data.asOf);return <button className="action-row" key={c.id} onClick={()=>setSelected(c)}><span className={"action-icon "+(r.days<0?"red":"amber")}>{r.days<0?<TriangleAlert size={17}/>:<Clock3 size={17}/>}</span><span className="action-text"><b>{c.route}<span>{c.tour}</span></b><small>{shortDate(c.departure)} departure · {c.booked}/{c.seats} seats booked</small></span><span className="action-deadline"><b>{r.days<0?Math.abs(r.days)+"d overdue":r.days===0?"Due today":r.days+"d to release"}</b><small>{shortDate(c.releaseDate)}</small></span><ChevronRight size={14}/></button>})}
 {attention.length===0&&<p className="empty-inline">No urgent commitments under these filters.</p>}</section>
 <section className="panel"><div className="panel-title"><div><h2>Commercial position</h2><p>Air component only · excludes land costs and overheads</p></div><TrendingUp size={19} color="#9bb0c0"/></div><div className="commercial-kpis"><div><span>Forecast air revenue</span><b>{money(totals.forecastRevenue,true)}</b></div><div><span>Budget air revenue</span><b>{money(totals.budget,true)}</b></div></div><div className="budget-track"><span style={{width:Math.min(100,totals.forecastRevenue/totals.budget*100)+"%"}}/></div><div className="budget-note"><b>{(totals.forecastRevenue/totals.budget*100).toFixed(1)}% of budget</b><span>{money(totals.forecastRevenue-totals.budget,true)} variance</span></div><div className="commercial-footer"><span>Potential release benefit</span><b>{money(totals.benefit,true)}</b><button onClick={()=>navigate("Scenario planner")} aria-label="Open scenario planner"><ArrowUpRight size={17}/></button></div></section></div>
 <section className="panel route-summary"><div className="panel-title"><div><h2>Route performance at a glance</h2><p>Find the gap between current bookings and expected departure load</p></div><span className="chip">{routeIds.length} routes</span></div><div className="route-cards">{routeIds.map(id=>{const cs=rows.filter(c=>c.route===id),t=summarize(cs,data.asOf),r=data.routes.find(x=>x.id===id)!;return <button key={id} className="route-card" onClick={()=>{setSearch(id);navigate("Flight inventory")}}><div><Plane size={15}/><b>{id}</b><ChevronRight size={13}/></div><span>{r.destination}</span><div className="route-progress"><i style={{width:t.utilisation+"%"}}/></div><small><b>{t.utilisation.toFixed(0)}%</b> booked<span>{Math.round(t.forecast/t.seats*100)}% forecast</span></small></button>})}</div></section>
 </>}
 {view==="Flight inventory"&&<>
 <div className="section-toolbar"><div className="search-input"><Search size={17}/><input aria-label="Search inventory" placeholder="Search route, tour, airline or contract…" value={search} onChange={e=>setSearch(e.target.value)}/></div><Picker label="Inventory status" value={risk} onChange={setRisk} options={[{value:"all",label:"All commitments"},{value:"due",label:"Due within 14 days"},{value:"overdue",label:"Deadline passed"},{value:"release",label:"Release opportunities"},{value:"reviewed",label:"Reviewed on this device"}]}/><span className="muted small">{filtered.length} results</span></div>
 <section className="panel inventory-panel"><Table><TableHeader><TableRow><TableHead>Route / tour</TableHead><TableHead>Departure</TableHead><TableHead><button className="table-sort" onClick={()=>setSortAsc(!sortAsc)}>Release date<ArrowDownUp size={12}/></button></TableHead><TableHead>Booked load</TableHead><TableHead>Forecast</TableHead><TableHead>Unbooked value</TableHead><TableHead>Status</TableHead><TableHead><span className="sr-only">Details</span></TableHead></TableRow></TableHeader><TableBody>
 {filtered.slice((page-1)*8,page*8).map(c=>{const r=recommend(c,data.asOf);return <TableRow key={c.id}><TableCell><button className="table-route" onClick={()=>setSelected(c)}><b>{c.route}</b><span>{c.tour}</span><small>{c.id} · {c.airline}</small></button></TableCell><TableCell>{shortDate(c.departure)}<span className="table-sub">{c.departure.slice(0,4)}</span></TableCell><TableCell><span className={r.days<0?"red-text":r.days<=14?"amber-text":""}>{shortDate(c.releaseDate)}</span><span className="table-sub">{r.days<0?Math.abs(r.days)+" days passed":r.days+" days away"}</span></TableCell><TableCell><div className="load-cell"><b>{c.booked} / {c.seats}</b><span>{Math.round(c.booked/c.seats*100)}%</span></div><div className="table-progress"><span style={{width:c.booked/c.seats*100+"%"}}/></div></TableCell><TableCell><b>{c.forecastPax} pax</b><span className="table-sub">{c.forecastLow}–{c.forecastHigh} illustrative range</span></TableCell><TableCell>{money(r.unbooked)}</TableCell><TableCell>{reviewed.includes(c.id)?<span className="reviewed-tag"><Check size={12}/>Reviewed</span>:<Badge status={r.status}/>}</TableCell><TableCell><button className="icon-btn" aria-label={"View "+c.id} onClick={()=>setSelected(c)}><ChevronRight size={18}/></button></TableCell></TableRow>})}
 </TableBody></Table>{filtered.length===0&&<div className="empty"><Search size={25}/><h2>No matching commitments</h2><button className="btn" onClick={()=>{setSearch("");setRisk("all")}}>Clear inventory filters</button></div>}
 <div className="pagination"><span>{filtered.length?((page-1)*8+1)+"–"+Math.min(page*8,filtered.length)+" of "+filtered.length:"0 records"}</span><div><button className="btn" disabled={page===1} onClick={()=>setPage(page-1)}>Previous</button><span>Page {page} of {Math.max(1,Math.ceil(filtered.length/8))}</span><button className="btn" disabled={page*8>=filtered.length} onClick={()=>setPage(page+1)}>Next</button></div></div></section><div className="notice"><Info size={16}/><p>Gross unbooked value is unsold seats × contracted return air cost. It is a commitment measure, not an expected loss. Review flags are local annotations and do not change airline inventory.</p></div>
 </>}
 {view==="Demand forecast"&&<>
 <div className="data-banner"><Database size={18}/><div><b>BITRE actuals through June 2026</b><span>Latest downloaded release: 18 Sep 2026 · July–September remain model estimates at this snapshot.</span></div><a href={data.provenance.sourceUrl} target="_blank" rel="noreferrer">Official source<ExternalLink size={13}/></a></div>
 <div className="metrics forecast-metrics"><Metric label="Holdout forecast error" value={wape.toFixed(1)+"%"} note="WAPE · Jan–Jun 2026, unseen for model selection" icon={ChartNoAxesCombined}/><Metric label="Real route observations" value={number(data.market.filter(m=>activeMarketRoutes.includes(m.route)).length)} note="Monthly outbound passenger movements" icon={Database}/><Metric label="Forecast horizon" value="12 months" note="Jul 2026 – Jun 2027 · market demand" icon={CalendarDays}/><Metric label="Selected model" value="Seasonal" note="Won 2025 validation on each route" icon={ShieldCheck}/></div>
 <section className="panel"><div className="panel-title"><div><h2>Where demand is heading</h2><p>Outbound passenger movements · all carriers · no tourism-only attribution</p></div><Picker label="Market route" value={forecastRoute} onChange={setForecastRoute} options={[{value:"all",label:"All filtered routes"},...routeIds.map(id=>({value:id,label:id}))]}/></div><div className="market-chart chart-container" role="img" aria-label="Monthly actual outbound passenger movements and future market demand estimates"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={marketChart} margin={{left:-6,right:20,top:15,bottom:10}}><CartesianGrid vertical={false} stroke="#edf2f6"/><XAxis dataKey="month" interval={4} axisLine={false} tickLine={false} tick={{fontSize:11,fill:"#8094a5"}}/><YAxis axisLine={false} tickLine={false} tickFormatter={n=>Math.round(n/1000)+"k"} tick={{fontSize:11,fill:"#8094a5"}}/><Tooltip {...chartTooltip} formatter={(v,name)=>[Array.isArray(v)?v.map(number).join(" – "):number(Number(v)),name==="band"?"Indicative error envelope":name]}/><Area dataKey="band" fill="#dce9ff" stroke="none" name="Indicative error envelope" legendType="none"/><Line dataKey="Actual" stroke="#2563eb" strokeWidth={2.5} dot={false} connectNulls={false}/><Line dataKey="Forecast" stroke="#33a594" strokeWidth={2.5} strokeDasharray="5 4" dot={false} connectNulls={false}/><ReferenceLine x="Jun 26" stroke="#96aabd" strokeDasharray="3 3" label={{value:"Last actual",fontSize:10,fill:"#728b9f",position:"insideTopLeft"}}/><Legend iconSize={8} wrapperStyle={{fontSize:12}}/></ComposedChart></ResponsiveContainer></div><div className="chart-note"><Info size={13}/>Shaded envelope uses 2025 forecast errors. It is an indicative range, not a guaranteed confidence interval; aggregate bands sum route limits.</div></section>
 <div className="forecast-details"><section className="panel"><div className="panel-title"><div><h2>Accuracy you can inspect</h2><p>Models selected on 2025 validation, evaluated on Jan–Jun 2026</p></div><a className="text-btn" href="/reports/forecast_backtest.csv" download>Download backtest<Download size={13}/></a></div><Table><TableHeader><TableRow><TableHead>Route</TableHead><TableHead>Selected WAPE</TableHead><TableHead>Trend WAPE</TableHead><TableHead>Band coverage</TableHead></TableRow></TableHeader><TableBody>{data.modelScores.filter(s=>activeMarketRoutes.includes(s.route)).map(s=><TableRow key={s.route}><TableCell><b>{s.route}</b></TableCell><TableCell>{s.wape.toFixed(1)}%</TableCell><TableCell>{s.trendWape.toFixed(1)}%</TableCell><TableCell><span className={s.holdoutCoverage<80?"amber-text":""}>{s.holdoutCoverage.toFixed(0)}%</span><span className="table-sub">of six holdout months</span></TableCell></TableRow>)}</TableBody></Table><p className="method-note">WAPE = total absolute error ÷ total actual passengers. Low envelope coverage on some routes means the interval is too narrow; use wider commercial buffers.</p></section>
 <section className="panel seasonality"><div className="panel-title"><div><h2>The seasonality signal</h2><p>2025 actual demand ÷ each route's monthly mean</p></div></div><div className="heatmap">{["","J","F","M","A","M","J","J","A","S","O","N","D"].map((m,i)=><span key={"h"+i} className="heat-header">{m}</span>)}{data.routes.filter(r=>activeMarketRoutes.includes(r.id)).map(r=>{const vals=data.market.filter(m=>m.route===r.id&&m.month.startsWith("2025"));const avg=sum(vals,m=>m.outbound)/12;return <div className="heat-row" key={r.id}><b>{r.id}</b>{Array.from({length:12},(_,i)=>{const v=vals.find(x=>Number(x.month.slice(5))===i+1)?.outbound||0;const ratio=v/avg;return <span key={i} title={r.id+" · "+(i+1)+"/2025: "+number(v)+" pax ("+ratio.toFixed(2)+"× mean)"} style={{background:"rgba(37,99,235,"+Math.max(.08,Math.min(.75,(ratio-.6)*.9))+")"}}>{ratio.toFixed(1)}</span>})}</div>})}</div><div className="heat-legend">Lower demand<span/>Higher demand</div><p className="method-note">A value of 1.2 is 20% above the route's monthly mean. Market seasonality does not establish a touring conversion rate.</p></section></div>
 </>}
 {view==="Scenario planner"&&<>
 <div className="scenario-grid"><section className="panel scenario-controls"><span className="eyebrow">SET THE ASSUMPTIONS</span><h2>A decision before a commitment.</h2><p className="muted">Use the simulated booking forecast as a starting point, then test demand and seat protection.</p><label className="slider-label">Change in expected demand<b>{uplift>0?"+":""}{uplift}%</b></label><Slider aria-label="Change in expected demand" value={[uplift]} onValueChange={v=>setUplift(v[0])} min={-35} max={35} step={1}/><div className="slider-scale"><span>−35% downside</span><span>+35% upside</span></div>
 <label className="slider-label">Safety buffer per departure<b>{buffer} seats</b></label><Slider aria-label="Safety buffer seats" value={[buffer]} onValueChange={v=>setBuffer(v[0])} min={0} max={8} step={1}/><div className="slider-scale"><span>Lean inventory</span><span>More protection</span></div><label className="control-label">Seat strategy</label><Picker label="Seat strategy" value={strategy} onChange={setStrategy} options={[{value:"release",label:"Release eligible surplus"},{value:"retain",label:"Retain all seats"}]}/><div className="scenario-rules"><ShieldCheck size={18}/><p>Release only before the deadline. Protect confirmed bookings and minimum group size. Cap releases at the simulated contract allowance of 50%.</p></div><button className="text-btn" onClick={()=>{setUplift(0);setBuffer(2);setStrategy("release")}}><RotateCcw size={13}/>Reset to base assumptions</button></section>
 <section className="panel scenario-results"><div className="panel-title"><div><h2>The commercial effect</h2><p>Same demand scenario, compared with retaining all seats</p></div><span className="chip">Illustrative</span></div><div className="scenario-headline"><span>Contribution improvement</span><strong className={benefit<0?"red-text":""}>{money(benefit)}</strong><p>After release fees of 12% of seat cost</p></div><div className="scenario-result-grid"><div><span>Seats to release</span><b>{number(releases)}</b></div><div><span>Seats retained</span><b>{number(sum(scenario,r=>r.retained))}</b></div><div><span>Expected passengers served</span><b>{number(sum(scenario,r=>r.served))}</b></div><div><span>Demand above retained capacity</span><b>{number(sum(scenario,r=>r.missed))}</b></div></div><div className="contribution-comparison"><div><span>Retain all seats</span><b>{money(baselineMargin)}</b></div><div><span>Your scenario</span><b>{money(scenarioMargin)}</b></div></div><div className="scenario-footnote"><Info size={15}/><span>Air contribution = served passengers × air selling price − retained seat cost − release fees. It excludes tour land costs, marketing, taxes outside the assumed cost, and overheads.</span></div></section></div>
 <section className="panel"><div className="panel-title"><div><h2>From scenario to review list</h2><p>Highest contribution opportunities · every decision is constrained by the contract</p></div><button className="text-btn" onClick={()=>{const csv=["Contract,Route,Demand,Release,Retained,Contribution AUD,Benefit AUD",...scenario.map(r=>[r.c.id,r.c.route,r.demand,r.release,r.retained,r.margin,r.benefit].join(","))].join("\n");download(csv,"touring-scenario.csv");toast.success("Scenario exported")}}>Export scenario<Download size={13}/></button></div><Table><TableHeader><TableRow><TableHead>Route</TableHead><TableHead>Departure</TableHead><TableHead>Expected pax</TableHead><TableHead>Release</TableHead><TableHead>Retain</TableHead><TableHead>Benefit</TableHead><TableHead>Constraint</TableHead></TableRow></TableHeader><TableBody>{[...scenario].sort((a,b)=>b.benefit-a.benefit).slice(0,6).map(r=><TableRow key={r.c.id}><TableCell><button className="table-route" onClick={()=>setSelected(r.c)}><b>{r.c.route}</b><small>{r.c.id}</small></button></TableCell><TableCell>{shortDate(r.c.departure)}</TableCell><TableCell>{r.demand}</TableCell><TableCell>{r.release} seats</TableCell><TableCell>{r.retained} seats</TableCell><TableCell className="green-text">{money(r.benefit)}</TableCell><TableCell>{r.days<0?"Release window closed":r.release===r.c.maxRelease?"Contract release cap":r.release===0?"Protected demand":"Demand + "+buffer+" seat buffer"}</TableCell></TableRow>)}</TableBody></Table></section>
 <div className="notice"><TriangleAlert size={16}/><p>These are sensitivity estimates, not verified savings. All contract fees, limits, fares and booking curves are simulated. A commercial user must verify actual fare rules and obtain Product Manager approval before releasing seats.</p></div>
 </>}
 {view==="Data quality"&&<>
 <div className="metrics"><Metric label="Raw booking records" value={number(data.quality.rawRecords)} note="Simulated source feed before validation" icon={Database}/><Metric label="Accepted records" value={number(data.quality.acceptedRecords)} note="Reconciled to 748 confirmed passengers" icon={CircleCheck}/><Metric label="Quarantined records" value={String(data.quality.quarantined.length)} note="Excluded, with reason and record ID retained" icon={TriangleAlert}/><Metric label="Market completeness" value="100%" note="252 / 252 expected route-month records" icon={ShieldCheck}/></div>
 <div className="pipeline-strip">{[{label:"1. Ingest",detail:"BITRE XLSX + booking feed"},{label:"2. Validate",detail:"Schema, keys, dates, passenger totals"},{label:"3. Reconcile",detail:"Bookings → contract passenger load"},{label:"4. Publish",detail:"SQLite, CSV, Excel, dashboard"}].map(p=><div key={p.label}><CircleCheck size={18}/><b>{p.label}</b><small>{p.detail}</small></div>)}</div>
 <div className="lower-grid"><section className="panel"><div className="panel-title"><div><h2>Exception register</h2><p>Deliberately seeded defects, detected by the reproducible pipeline</p></div><span className="chip">3 resolved by quarantine</span></div><Table><TableHeader><TableRow><TableHead>Record</TableHead><TableHead>Rule</TableHead><TableHead>Action</TableHead></TableRow></TableHeader><TableBody>{data.quality.quarantined.map((q,i)=><TableRow key={q.record+i}><TableCell className="mono">{q.record}</TableCell><TableCell>{q.rule}</TableCell><TableCell><span className="status warning">{q.action}</span></TableCell></TableRow>)}</TableBody></Table></section>
 <section className="panel"><div className="panel-title"><div><h2>Data controls</h2><p>Checked at the correct grain</p></div></div>{["Route + month is unique","Inbound + outbound = total passenger movements","No missing months from Jan 2023 to Jun 2026","Accepted booking IDs are unique","Every accepted booking maps to a contract","Confirmed booking passengers match each contract load"].map(s=><div className="quality-rule" key={s}><CircleCheck size={16}/><span>{s}</span><b>Passed</b></div>)}</section></div>
 <section className="panel lineage"><div className="panel-title"><div><h2>Source lineage</h2><p>Clear ownership, provenance and refresh boundaries</p></div></div><div className="lineage-grid"><div><span className="eyebrow">PUBLIC SOURCE</span><h3>Australian international airline activity</h3><p>{data.provenance.publisher}</p><dl><dt>Measured period</dt><dd>Jan 2023 – Jun 2026</dd><dt>Published / retrieved</dt><dd>18 Sep / 9 Oct 2026</dd><dt>Source grain</dt><dd>City pair × calendar month</dd><dt>Selected measure</dt><dd>Outbound revenue passenger movements</dd></dl><a className="text-btn" href={data.provenance.sourceUrl} target="_blank" rel="noreferrer">View original publication<ExternalLink size={13}/></a></div><div><span className="eyebrow">SIMULATED SOURCE</span><h3>Illustrative touring operations</h3><p>48 contracts, 748 bookings and prior-year comparators</p><dl><dt>Snapshot</dt><dd>9 Oct 2026</dd><dt>Reproducibility</dt><dd>Fixed random seed: 417</dd><dt>Commercial grain</dt><dd>Contract × departure + passenger booking</dd><dt>Decision owner</dt><dd>Product Manager; coordinator prepares review</dd></dl><p className="method-note">No private Flight Centre data, live fares, booking API or personal information is used.</p></div></div><div className="checksum"><span>Source SHA-256</span><code>{data.provenance.sha256}</code></div></section>
 </>}
 {view==="Project & methodology"&&<ProjectDetails/>}
 </>}
 </div><footer>Independent portfolio project · Commercial records are simulated. <span>TOURING CONTROL · AUD</span></footer>
 </main>
 <Sheet open={!!selected} onOpenChange={open=>{if(!open)setSelected(null)}}><SheetContent className="detail-sheet"><SheetHeader><span className="eyebrow">COMMITMENT REVIEW</span><SheetTitle>{selected?.route}</SheetTitle><SheetDescription>{selected?.tour}<br/>{selected?.id} · Simulated contract</SheetDescription></SheetHeader>{selected&&<ContractDetails contract={selected} reviewed={reviewed.includes(selected.id)} onReview={()=>markReviewed(selected.id)}/>}</SheetContent></Sheet>
 </SidebarProvider>;
}

function ContractDetails({contract:c,reviewed,onReview}:{contract:Contract;reviewed:boolean;onReview:()=>void}){
 const r=recommend(c,data.asOf);const transactions=data.bookings.filter(b=>b.contractId===c.id);
 const channels=["Retail","Online","Trade"].map(ch=>({channel:ch,count:sum(transactions.filter(b=>b.channel===ch),b=>b.passengers)}));
 return <div className="detail-body"><Badge status={r.status}/><dl className="detail-facts"><dt>Departure</dt><dd>{shortDate(c.departure)} {c.departure.slice(0,4)}</dd><dt>Release deadline</dt><dd className={r.days<0?"red-text":""}>{shortDate(c.releaseDate)} {r.days<0?" · passed":""}</dd><dt>Airline / owner</dt><dd>{c.airline} / {c.owner}</dd><dt>Booked / committed</dt><dd>{c.booked} / {c.seats} passengers</dd><dt>Forecast load</dt><dd>{c.forecastPax} pax ({c.forecastLow}–{c.forecastHigh})</dd><dt>Air cost / selling price</dt><dd>{money(c.unitCost)} / {money(c.sellPrice)}</dd><dt>Unbooked commitment</dt><dd>{money(r.unbooked)}</dd></dl>
 <div className="recommendation"><span className="eyebrow">BASE-CASE RECOMMENDATION</span><h3>{r.days<0?"Escalate to Product Manager":r.release?"Review release of "+r.release+" seats":"Retain current commitment"}</h3><p>{r.days<0?"The contractual release window has passed. Confirm supplier terms and assess promotion or renegotiation; the model assumes no release is available.":r.release?"Retain "+r.retained+" seats for "+r.demand+" expected passengers and a two-seat safety buffer.":"Expected passenger demand and the safety buffer require the current commitment."}</p><div><span>Potential contribution benefit</span><b>{money(r.benefit)}</b></div></div>
 <h3>Contract assumptions</h3><p className="method-note">Minimum group: {c.minGroup} · maximum release: {c.maxRelease} seats · release fee: {money(c.releaseFee)} per seat. Return air cost is per passenger. These assumptions are simulated and do not represent this airline's published terms.</p>
 <h3>Booking channel mix</h3>{channels.map(ch=><div className="channel-row" key={ch.channel}><span>{ch.channel}</span><div><i style={{width:ch.count/c.booked*100+"%"}}/></div><b>{ch.count}</b></div>)}
 <button className={"btn "+(!reviewed?"primary":"")} onClick={onReview}><Check size={15}/>{reviewed?"Reopen review":"Mark as reviewed"}</button><small className="local-note">Saved on this browser only. No airline booking is changed.</small></div>;
}

function ProjectDetails(){return <div className="project-content">
 <section className="project-intro panel"><span className="eyebrow">THE REAL BUSINESS PROBLEM</span><h2>Demand is uncertain.<br/>The seat commitment is not.</h2><p>A touring operator commits airline seats before every passenger books. A weak-selling departure may tie up working capital and erode air contribution. A premature release may leave a successful tour short of capacity. Booking data, contract dates and sales reports often sit in different systems, making the decision harder to see in time.</p><div className="project-question">Which seats should we keep, release or escalate—and what is the commercial trade-off?</div></section>
 <Tabs defaultValue="solution"><TabsList className="project-tabs"><TabsTrigger value="solution">Solution & value</TabsTrigger><TabsTrigger value="method">How it works</TabsTrigger><TabsTrigger value="career">Interview walkthrough</TabsTrigger></TabsList>
 <TabsContent value="solution"><div className="project-columns"><section className="panel"><h2>A coordinator's decision workflow</h2><ol className="workflow"><li><b>Bring records together</b><p>Join airline commitments and passenger bookings by contract ID. Keep one departure-level source of truth.</p></li><li><b>Identify exposure early</b><p>Measure load, unsold seat cost and release windows. Flag expired deadlines for escalation.</p></li><li><b>Forecast and challenge</b><p>Use booking pace for the illustrative tour forecast. Compare public market models with out-of-sample accuracy.</p></li><li><b>Make a reviewable recommendation</b><p>Protect sold seats, group minima and a demand buffer. Calculate retained costs, fees and contribution.</p></li><li><b>Distribute and improve</b><p>Export the action queue and Excel report. Review exceptions and record recommendations consistently.</p></li></ol></section><section className="panel"><h2>Capabilities matched to the role</h2><div className="capability-list">{[["Inventory coordination","48 flight commitments, deadlines and passenger loads"],["Commercial analysis","Air revenue, budget variance, contribution and exposure"],["Forecasting","Seasonality, model selection, WAPE and error envelopes"],["Excel reporting","SUMIFS reporting, live release formulas and Pivot-ready tables"],["Data governance","Grain checks, reconciliation, quarantine and source hash"],["Stakeholder communication","Named ownership, actionable review and decision rationale"]].map(([a,b])=><div key={a}><CircleCheck size={17}/><span><b>{a}</b><p>{b}</p></span></div>)}</div><div className="success-metrics"><h3>What a real pilot would measure</h3><p>On-time deadline reviews, avoidable expired seat cost, forecast WAPE, capacity shortfalls and time spent preparing reports. Establish a baseline before claiming any savings.</p></div></section></div></TabsContent>
 <TabsContent value="method"><section className="panel methodology"><h2>Two forecasts, two different questions</h2><div className="method-grid"><div><h3>Public market demand</h3><p>BITRE provides monthly outbound passenger movements by Australian and foreign city. Use Jan 2023–Dec 2024 as initial history, rolling 2025 forecasts for model selection, and Jan–Jun 2026 as a final holdout.</p><p>Compare a seasonal naive model with a trend-adjusted seasonal model. The trend multiplier is the mean YoY ratio of the last six available months, clipped to 0.8–1.2. Each prediction uses only data already observed.</p><p>All six routes select the seasonal baseline on 2025 validation. Forecast the next 12 months from the prior-year month. Show measured holdout error and the coverage of a validation-calibrated error envelope.</p></div><div><h3>Touring seat demand</h3><p>The illustrative departure forecast uses confirmed bookings divided by the assumed fraction booked at that lead time, capped at contracted seats. The curve ranges from 26% booked at 180 days to 94% at 30 days.</p><p>It is not learned from Flight Centre bookings and does not convert market traffic into tour passengers. Actual implementation requires historical tour booking snapshots, cancellations, promotions and unconstrained demand.</p><p>The planner changes expected passenger demand and protects a chosen safety buffer. It then applies deadline, group-size and release-cap constraints.</p></div></div><div className="formula-box"><p>Release seats = max(0, min(contract release cap, commitment − max(booked, minimum group, forecast demand + buffer)))</p><p>Air contribution = min(demand, retained seats) × selling price − retained seats × air cost − released seats × release fee</p></div><h3>Boundaries that matter</h3><p>Public passenger movements may include connecting travellers and are not tourism-only. The publication has a reporting lag. Tokyo and Seoul are city aggregates; route codes TYO and SEL describe city pairs, not specific airports. Commercial contracts, carriers, fares, budgets and prior-year comparators are illustrative. Tour names are fictional. Release rules are not airline-specific terms. No savings, revenue uplift or company deployment is claimed.</p></section></TabsContent>
 <TabsContent value="career"><section className="panel interview"><h2>A focused five-minute demonstration</h2><ol className="workflow"><li><b>Start with the problem · 45 seconds</b><p>“I built Touring Control to explore how a touring business can identify seat exposure before supplier release deadlines, while preserving capacity for demand.”</p></li><li><b>Show the commercial overview · 60 seconds</b><p>Explain commitment versus expected loss, booked utilisation, forecast revenue and budget variance. Filter to Brisbane to show a stakeholder-specific view.</p></li><li><b>Review a flight commitment · 60 seconds</b><p>Open a low-selling Japan departure. Explain the release window, booking pace, protected passengers, assumed fees and why a Product Manager owns the decision.</p></li><li><b>Challenge the forecast · 60 seconds</b><p>Show genuine BITRE route observations and the validation/holdout split. Explain why the baseline won and why low interval coverage matters.</p></li><li><b>Test a decision and show controls · 75 seconds</b><p>Increase demand in the planner, observe reduced releases, then open the exception register and Excel report. State what real company data you would need for a pilot.</p></li></ol><div className="success-metrics"><h3>Suggested portfolio description</h3><p>Designed a commercial flight-inventory decision-support prototype combining official Australian route data with a reproducible simulated touring portfolio. Built forecast validation, contract-constrained release scenarios, data-quality controls and an interactive dashboard with Excel and CSV reporting.</p></div></section></TabsContent></Tabs>
 <section className="panel project-downloads"><div><h2>The project evidence pack</h2><p>Take the calculations and source records beyond the dashboard.</p></div><div className="download-links"><a className="btn primary" href="/reports/touring-control.xlsx" download><Download size={15}/>Excel reporting pack</a><a className="btn" href="/reports/market_actuals.csv" download><Download size={15}/>Real market data</a><a className="btn" href="/reports/case-study.md" download><BookOpen size={15}/>Business case</a></div></section>
 <div className="source-links"><span>Research foundation</span><a href={data.provenance.sourceUrl} target="_blank" rel="noreferrer">BITRE international airline activity<ExternalLink size={12}/></a><a href="https://mytouring.com.au/" target="_blank" rel="noreferrer">My Touring flight-inclusive packages<ExternalLink size={12}/></a><a href="https://www.qantas.com/en-au/book/flights/group-travel" target="_blank" rel="noreferrer">Qantas group travel conditions<ExternalLink size={12}/></a></div>
 </div>}
