[theme]
base = "light"
primaryColor = "#d71920"
backgroundColor = "#f5f7fa"
secondaryBackgroundColor = "#ffffff"
textColor = "#253746"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
